name: generative_ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - lightgbm
  - jupyterlab
  - notebook
  - scipy
  - statsmodels
  - plotly
  - ipywidgets
  - pip
  - pip:
      - catboost
      - mlxtend
      - optuna
